sudo: false
language: c
os:
- linux
- osx

git:
  depth: 3

script: ./bin/run-tests --tap ./test

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/901694477147612308dd
    on_success: change
    on_failure: always
    on_start: never
